#!/bin/bash
ERROR=-1

# numero minimo di argomenti
MINARGS=1 

# numero massimo di argomenti (input_file, output_file e opzione check-array-bounds)
MAXARGS=1

#numero di argomenti con cui e' stato chiamato lo script
ARGC=$#

if [ $ARGC -lt $MINARGS ] || [ $ARGC -gt $MAXARGS ]; then
        echo "impi: no input files"
	exit $ERROR
fi

if [ $ARGC -eq $MAXARGS ] && [ -f $1 ]; then
    camlp4 main.cmo < $1
    exit 0
else 
    echo "impi: file" $1 ": no such file"
    exit $ERROR
fi


